name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  trigger-sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger SonarCloud Analysis
        run: echo "Trigger SonarCloud Analysis"

  sonarcloud:
    runs-on: ubuntu-latest
    needs: trigger-sonarcloud  # Alinhado corretamente com a lista de jobs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Analyze with SonarCloud
        run: |
          if [ -z "${GITHUB_ACTOR}" ]; then
            mvn sonar:sonar \
              -Dsonar.projectKey=eduardojuhn_Health-API- \
              -Dsonar.organization=eduardojuhn \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.branch.name=main
          else
            echo "Skipping SonarCloud analysis for GitHub Actions workflow"
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
